#!/usr/bin/perl -w

use lib '../lib';

use strict;
use v5.10;

use NSMF::Node;
use NSMF::Node::Component::CXTRACKER;
use NSMF::Util;

my $config_file = '../etc/cxtracker.yaml';

# Creating new CXTRACKER Node
my $cxt = NSMF::Node::Component::CXTRACKER->new();

# Loading configuration variables
$cxt->load_config($config_file);

# Connect and Authenticate
$cxt->sync;
$cxt->start;

