#!/usr/bin/perl -w -I../common/NSMFcommon/
# ----------------------------------------------------------------------
# This file is a part of The NSMFramework
# Copyright (C) 2010, Edward Fjellskål <edwardfjellskaal@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# ----------------------------------------------------------------------

use strict;
use warnings;
use POSIX qw(setsid);
use IO::Socket::INET;
use Getopt::Long;
use DateTime;
use NSMFcommon::Config;
use NSMFcommon::Dirs;
use NSMFcommon::Daemon;

=head1 NAME

 nsmf-cxtracker

=head1 VERSION

 0.1

=head1 SYNOPSIS

 $ nsmf-cxtracker [options]

 OPTIONS:

 -c|--configfile : spesify path to configfile
 -h|--help       : this help message
 --version       : show version

=cut

# default config
our $CONFIGFILE    = qq(/etc/nsmf-node/cxtracker.conf);
our $DEBUG         = 1;
our $DAEMON        = 0;
our $NSMFSERVER    = qq(127.0.0.1);
our $NSMFPORT      = qq(10101);
our $NODENAME      = qq(default);
our $NETGROUP      = qq(EXT_NET);
our $CXTDIR        = qq(/var/lib/cxtracker/$NODENAME/);
our $CXTDIRFAIL    = qq($CXTDIR/failed/);
our $CHECKFILES    = 30;
our $PINGSERVER    = 5000;
our $LOGFILE       = qq(/var/log/nsmf-node/cxtracker-$NODENAME.log);
our $PIDFILE       = qq(/var/run/nsmf-cxtracker-$NODENAME.pid);

Getopt::Long::GetOptions(
    'configfile|c=s'        => \$CONFIGFILE,
);

# read config
my $CONFIG = {};
$CONFIG = NSMFcommon::Config::load_config("$CONFIGFILE",$DEBUG);
$NODENAME = $CONFIG->{'NODENAME'} if (defined $CONFIG->{'NODENAME'});
$NETGROUP = $CONFIG->{'NETGROUP'} if (defined $CONFIG->{'NETGROUP'});
$NSMFSERVER = $CONFIG->{'NSMFSERVER'} if (defined $CONFIG->{'NSMFSERVER'});
$NSMFPORT = $CONFIG->{'NSMFPORT'} if (defined $CONFIG->{'NSMFPORT'});
$CXTDIR = $CONFIG->{'CXTDIR'} if (defined $CONFIG->{'CXTDIR'});
$LOGFILE = $CONFIG->{'LOGFILE'} if (defined $CONFIG->{'LOGFILE'});
$PIDFILE = $CONFIG->{'PIDFILE'} if (defined $CONFIG->{'PIDFILE'});
$CHECKFILES = $CONFIG->{'CHECKFILES'} if (defined $CONFIG->{'CHECKFILES'});
$PINGSERVER = $CONFIG->{'PINGSERVER'} if (defined $CONFIG->{'PINGSERVER'});

# Prepare

# Signal handlers
use vars qw(%sources);
#$SIG{"HUP"}   = \&recreate_merge_table;
$SIG{"INT"}   = sub { gameover($DEBUG, "INT" ) };
$SIG{"TERM"}  = sub { gameover($DEBUG, "TERM") };
$SIG{"QUIT"}  = sub { gameover($DEBUG, "QUIT") };
$SIG{"KILL"}  = sub { gameover($DEBUG, "KILL") };
#$SIG{"ALRM"}  = sub { dir_watch(); alarm $TIMEOUT; };

# Main program

# Check that all needed dirs exists
NSMFcommon::Dirs::check_dir_create_w ($CXTDIR);
NSMFcommon::Dirs::check_dir_create_w ($CXTDIRFAIL);
NSMFcommon::Dirs::check_dir_create_w ("/var/log/nsmf-node/");  # Needs to be fixed: Should find dir from $LOGFILE 
#NSMFcommon::Dirs::check_dir_create_w ("/var/run/");            # Needs to be fixed: Should find dir from $PIDFILE

NSMFcommon::Daemon::go_daemon ($LOGFILE,$PIDFILE) if $DAEMON;;

## if new file; try to connect to server (loop)...
# Start dir_watch() which looks for new session files and tries to send them to server.
warn "[*] Looking for session data in: $CXTDIR \n" if $DEBUG;
dir_watch();
exit;

=head1 FUNCTIONS

=head2 dir_watch

 Tries to connects to the nsmf-server and looks for new session data in $CXTDIR.
 If a new session files i found, it will try to send its data to the server.

=cut

sub dir_watch {
    #infinite loop

    my $SS = IO::Socket::INET->new( PeerAddr => $NSMFSERVER, PeerPort => $NSMFPORT, Proto => 'tcp');
    my $AUTHOK = send_auth($SS);

    while (1) {
        if (defined $SS && $AUTHOK) {
            my @FILES;
            # Open the directory
            if( opendir( DIR, $CXTDIR ) ) {
                # Find session files in dir (stats.eth0.1229062136)
                while( my $FILE = readdir( DIR ) ) {
                    next if( ( "." eq $FILE ) || ( ".." eq $FILE ) );
                    next unless ($FILE =~ /^stats\..*\.\d{10}$/);
                    push( @FILES, $FILE ) if( -f "$CXTDIR/$FILE" );
                }
                closedir( DIR );
            }
            # If we find any files, proccess...
            foreach my $FILE ( @FILES ) {
                my $starttime=time();
                print "[*] Found file: $CXTDIR/$FILE\n" if ($DEBUG);
                my $SESSIONSDATA = get_sessions("$CXTDIR/$FILE");
                my $endtime=time();
                my $processtime=$endtime-$starttime;
                print "[*] File $CXTDIR/$FILE processed in $processtime seconds\n" if ($DEBUG);
                $starttime=$endtime;
                my $result = send_data_to_server($DEBUG,$SESSIONSDATA,$SS);
                if ($result >= 1) {
                    print "[E] Error while sending sessiondata to server: $CXTDIR/$FILE -> $NSMFSERVER:$NSMFPORT\n";
                    print "[*] Skipping deletion of file: $CXTDIR/$FILE\n";
                }
                $endtime=time();
                $processtime=$endtime-$starttime;
                if ($result == 0) {
                    print "[*] Sessiondata sent in $processtime seconds\n" if ($DEBUG);
                    print "[W] Deleting file: $CXTDIR/$FILE\n";
                    unlink("$CXTDIR/$FILE") if $result == 0;
                }
                # Dont pool files to often, or to seldom...
                sleep 1; # FIXME delete when testing is done, add INET_ATON6 first :)
            }
        } else {
            print "[E] Could not connect/auth to server: $NSMFSERVER:$NSMFPORT, trying again in 15sec...\n";
            sleep 15;
            $SS->close() if defined $SS;
            $SS = IO::Socket::INET->new( PeerAddr => $NSMFSERVER, PeerPort => $NSMFPORT, Proto => 'tcp');
            if ( defined $SS ) {
                $AUTHOK = send_auth($SS);
            } else {
                $AUTHOK = 0;
            }
        }
    }
}

=head2 send_auth

 Sends the AUTH header to the NSMF server, just when connecting.

=cut

sub send_auth {
    my $SS = shift;
    my $line = qq();
    if (defined $SS) {
        my $HEADER = "AUTH CXTRACKER NSMF/1.0";
        print $SS "$HEADER\0";
        print "[*] Sent HEADER: '$HEADER'.\n" if $DEBUG;
        $SS->flush();
        sysread($SS, $line, 8192, length $line);
        chomp $line;
        $line =~ s/\r//;
        if ( $line =~ /200 OK ACCEPTED/ ) {
            print "[*] Server $NSMFSERVER sent response: '$line'.\n" if $DEBUG;
            #ID KEY NODENAME NETGROUP
            my $ID = "ID SHA256SECRETKEY NODENAME NETGROUP";
            print $SS "$ID\0";
            print "[*] Sent ID: '$ID'.\n" if $DEBUG;
            $SS->flush();
            $line = qq();
            sysread($SS, $line, 8192, length $line);
            chomp $line;
            $line =~ s/\r//;
            if ( $line =~ /200 OK ACCEPTED/ ) {
                return 1; #OK
            } else {
                return 0; #ERROR
            }
        } else {
            return 0; #ERROR
        }
    } else {
        return 0; #ERROR
    }
}

=head2 get_sessions

 This sub extracts the session data from a session data file.
 Takes $file as input parameter.

=cut

sub get_sessions {
    my $SFILE = shift;
    my $sessionsdata = q();

    if (open (FILE, $SFILE)) {
        my $filelen=`wc -l $SFILE |awk '{print \$1'}`;
        my $filesize=`ls -lh $SFILE |awk '{print \$5}'`;
        chomp $filelen;
        chomp $filesize;
        print "[*] File:$SFILE, Lines:$filelen, Size:$filesize\n" if $DEBUG;
        # Verify the data in the session files
        LINE:
        while (my $line = readline FILE) {
            chomp $line;
            $line =~ /^\d{19}/;
            unless($line) {
                warn "[*] Error: Not valid session start format in: '$SFILE'";
                next LINE;
            }
            my @elements = split/\|/,$line;
            unless(@elements == 15) {
                warn "[*] Error: Not valid Nr. of session args format in: '$SFILE'";
                next LINE;
            }
            # Things should be OK now to send to the SERVER
            if ( $sessionsdata eq "" ) {
                $sessionsdata = "$line";
            } else {
                $sessionsdata = "$sessionsdata\n$line";
            }
      }
      close FILE;
      print "Sessionsdata:\n$sessionsdata\n" if $DEBUG;
      return $sessionsdata;
      }
}

=head2 send_data_to_server

 Sends a chunck of $DATA to $Socket
 Returns 0 on success;

=cut

sub send_data_to_server {
    my ($DEBUG, $DATA, $SS) = @_;
    return 1 if not defined $SS;

    my $line = qq();
    my $HEADER = "POST DATA";

    $SS->say("$HEADER\0");
    $SS->flush();
    print "[*] Sent HEADER: '$HEADER'.\n" if $DEBUG;
    $line = qq();
    sysread($SS, $line, 8192, length $line);
    chomp $line;
    $line =~ s/\r//;
    if ( $line =~ /200 OK ACCEPTED/ ) {
        print $SS "$DATA\n.\r\n\0";
        $SS->flush();
        print "[*] Data sent.\n" if $DEBUG;
        $line = qq();
        sysread($SS, $line, 8192, length $line);
        chomp $line;
        $line =~ s/\r//;
        if ( $line =~ /200 OK ACCEPTED/ ) {
            print "[*] Server recived data OK.\n" if $DEBUG;
            return 0; #OK
        } else {
            print "[*] Server $NSMFSERVER sent bogus response to \"EOF\": '$line'.\n" if $DEBUG;
        }
    } else {
        print "[*] Server $NSMFSERVER sent bogus response to \"POST DATA\": '$line'.\n" if $DEBUG;
    }
    return 1; #ERROR
}

=head2 gameover

 Shutdown in a clean way.

=cut

sub gameover{
    my ($DAEMON, $sig) = @_;
    print "[*] Got $sig, Ending.\n";
    #File::Temp::cleanup();
    unlink($PIDFILE) if $DEBUG;
    #threads->exit();
    exit 0;
}

