#!/usr/bin/perl -w

use lib '../lib';

use strict;
use v5.10;

use NSMF::Node;
use NSMF::Node::SNORT;
use NSMF::Util;

my $config_file = '../etc/snort.yaml';

# Creating new SNORT Node
my $snortu = NSMF::Node::SNORT->new();

# Loading configuration variables
$snortu->load_config($config_file);

# Connect and Authenticate
$snortu->sync;
$snortu->start;

