#!/usr/bin/perl 

use lib '../lib';
use strict;
use warnings;

use NSMF::Node::CXTRACKER;
use Data::Dumper;

my $cxt = NSMF::Node::CXTRACKER->new;

$cxt->load_config('/etc/nsmf-node/cxtracker.conf');
$cxt->connect;
$cxt->authenticate;
$cxt->execute;

print Dumper $cxt;



