#!/usr/bin/perl -w

use lib '../lib';

use strict;
use v5.10;

use NSMF::Node::CXTRACKER;
use NSMF::Util;

my $config_file = '../etc/cxtracker.yaml';

# Creating new CXTRACKER Node
my $cxt = NSMF::Node::CXTRACKER->new;

# Loading configuration variables
$cxt->load_config($config_file);

# Connect and Authenticate
#  $cxt->connect;
#  $cxt->authenticate;
#  sync = connect + authenticate
#$cxt->sync;

# Node run method. Defined in Node/CXTRACKER.pm
#$cxt->run;

# Output Debug Information
 debug($cxt);

# Log to debug.log(default)
# log($cxt,'debug.log');
# 
# same as:
#
# log($cxt);



