#!/usr/bin/perl -w

use lib '../lib';

use strict;
use v5.10;

use NSMF;
use NSMF::Util;
use NSMF::Node::Daemonlogger;

my $config_file = '../etc/daemonlogger.yaml';

# Creating new Daemonlogger Node
my $cxt = NSMF::Node::Daemonlogger->new;

# Loading configuration variables
$cxt->load_config($config_file);

# Connect and Authenticate
$cxt->sync;
$cxt->start;

