#!/usr/bin/perl -w
use lib '../lib';
use strict;
use v5.10;
use NSMF::Node;
use NSMF::Util;

my $node = NSMF::Node->new;
debug($node);
$node->server('127.0.0.1');
$node->port(10101);
$node->connect();
$node->sync;
