#!/usr/bin/perl 
use lib '../lib';
use strict;
use warnings;
use NSMF::Error;
use NSMF::Node;
use NSMF::Net;
use NSMF::Auth;
use NSMF::Config;

my $config = load_config('/etc/nsmf-node/syscheck.conf');

die ("Config Failure") unless check_config($config);

my $conn       = NSMF::Net::connect($config);
my $auth_state = NSMF::Auth::send_auth($conn, $config);
my $node       = NSMF::Node->new;

$node->load_config($config);

print "Autentificado!\n" if $auth_state;
