#!/usr/bin/perl 
use lib 'lib';
use strict;
use warnings;
use NSMF::Node;
use FindBin;
my @OKMODULES = ();
my @MODULES = qw/ CXTRACKER SNORT SYSCHECK /;

sub load_runners {
    my @modules;
    foreach (@MODULES) { push @modules, "NSMF::Node::$_"; }
    #my @modules = map { "NSMFmodules::$_" } qw/CXTRACKER SNORT DAEMONLOGGER/;

    MODULE:
    for my $module (@modules) {
        local @INC = ("$FindBin::Bin/lib/");
        #eval { require $module };
        print "[*] Trying to load module: $module\n";
        eval "use $module";
        if ($@) {
            print "[E] Module $module not loaded/found: $@\n";
        } else {
            print "[*] Module $module loaded OK: $@\n";
            push @OKMODULES, $module;
        }
    }
    print "[*] Starting nsmf-server with modules: ";
    foreach my $name (@OKMODULES) { print "$name " if $name; }
    print "\n";
    eval "$_\:\:run" foreach (@OKMODULES);
    if($@){
    	die("[*] Couldnt execute runners");
    }
}
load_runners;
